config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  resources :users
  # get 'articles/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get('/articles', { to: 'articles#index' })
  # get "/articles/:id", to: "articles#show", as: :article
  root "articles#index"
  resources :articles do
    resources :comments
    # Defines the root path route ("/")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :user
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity # 422 Unprocessable Entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end


  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
      
    def set_article
      @article = Article.find(params[:id])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.new(comment_params)
    comment.user_id = current_user.id
    redirect_to article_path(@article) if comment.save
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
<div class="field form-group">
  <%= form.label :title %><br>
  <%= form.text_field :title,class:"form-control",placeholder:"Enter Article title" %>
  <% article.errors.full_messages_for(:title).each do |message| %>
  <div><%= message %></div>
  <% end %>
</div>

<div class="field form-group">
  <%= form.label :body %><br>
  <%= form.text_area :body, class:"form-control",placeholder:"Enter Article Description" %>
  <br>
  <% article.errors.full_messages_for(:body).each do |message| %>
  <div><%= message %></div>
  <% end %>
</div>
<div class="d-flex">
  <%= form.label :status, class:"mx-2" %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>
<div>
  <%= form.submit class:'btn btn-secondary' %>
</div>
<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarTogglerDemo03"
    aria-controls="navbarTogglerDemo03"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <div class="mr-auto mt-2 mt-lg-0 px-3">
        <%= link_to 'Blog', root_path, class:"navbar-brand" %>
      </div>
      <li class="nav-item active">
        <a class="nav-link" href="#">Home
          <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Article", new_article_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="d-flex">
      <input
        class="form-control me-2"
        type="search"
        placeholder="Search"
        aria-label="Search"
      >
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-center">Articles</h1>
<h2>Our blog has
  <%= Article.public_count %>
  articles and counting!</h2>
<table class="table table-striped table-bordered text-center table-hover">
  <thead class="table-dark" style="text-align:center;">
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Created_at</th>
      <th>Updated_at</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <% @articles.each do |article| %>
  <% unless article.archived? %>
  <tbody>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= article.created_at %></td>
      <td><%= article.updated_at %></td>
      <td>
        <%= link_to 'Show', article,class:"btn btn-primary" %>
      </td>
      <td>
        <%= link_to 'Edit', edit_article_path(article),class:"btn btn-success" %>
      </td>
      <td>
        <%= link_to 'Destroy', article, data: {
              method: :delete,
              confirm: "Are you sure?"
            },class:"btn btn-danger" %>
      </td>
    </tr>
  </tbody>
  <% end %>
  <% end %>
</table>
<%= link_to "New Article", new_article_path, class:"btn btn-secondary" %>

app/views/articles/new.html.erb
<h1>Add A New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @article.title %></h1>
  <p class="lead"><%= @article.body %></p>
  <hr class="my-4">
  <p>Created At:
    <%= @article.created_at %>
    | Updated At:
    <%= @article.updated_at %></p>
  <%= link_to 'Edit', edit_article_path(@article),class:"btn btn-warning" %>
  <%= link_to 'Destroy', @article, data: {
              method: :delete,
              confirm: "Are you sure?"
            },class:"btn btn-danger" %>
  <%= link_to 'Back', articles_path(@article),class:"btn btn-secondary" %>
  <br><br>
  <h2 class="text-center">Comments</h2>
  <%= render @article.comments %>
  <br><br>

  <h2 class="text-center">Add a New Comment:</h2>
  <%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<div class="card">
  <div class="card-header">
    <h4>Commenter</h4>
  </div>
  <div class="card-body">
    <h5 class="card-title">Published By: <%= comment.user.first_name + ' ' + comment.user.last_name %></h5>
    <p class="card-text">Description: <%= comment.body %></p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
  method: :delete,
                confirm: "Are you sure?"
              }, class:'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
<%# <div class="field form-group">
 %>
<div class="card">
  <div class="card-header">
    <h5><%= form.label :body %></h5>
  </div>
  <div class="card-body">
    <h5 class="card-title">
      <div class="form-floating">
        <div><%= form.text_area :body, class:'form-control', placeholder:'Leave a comment here' %></div>
      </div><br>
      <div class="d-flex">
        <%= form.label :status, class:'mx-2' %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
      </div>
      <br>
      <%= form.submit class:'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    >
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'articles/header' %>
  <div class="container">
  <br/>
    <%= 'Welcome ' + current_user.first_name if user_signed_in? %>
    <br/>
      <% if notice %></p>
      <%= render 'layouts/alerts' %>
      <% end %>
  </br>
    <%= yield %>
  </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>